openapi: 3.0.0
servers:
  - url: 'https://api.ibanfox.com/v1'
info:
  description: |-
    An API to perform operations on IBAN and SWIFT/BIC numbers.

    This source of this document is an OpenAPI 3 document which lives at https://github.com/theAPIfox/ibanfox
  version: '1.0'
  title: IBAN API
  contact:
    email: hello@ibanfox.com
    name: IBANfox Support
    url: 'https://ibanfox.com/contact'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'https://ibanfox.com/terms'
tags:
  - name: ibans
paths:
  '/ibans/{iban}/validity':
    get:
      summary: Validate an IBAN
      operationId: validateIban
      description: |-
        Given a candidate IBAN, returns the result of a validation, along with a suite of validation checks.

        Example:

        ```bash
        curl --request GET \
        --url 'https://api.ibanfox.com/v1/ibans/DE89370400440532013000/validity' \
        --header 'x-api-key: 46w4e65e4q54e6'
        ```
      parameters: []
      tags:
        - ibans
      responses:
        '200':
          description: |-
            IBAN validation performed successfully. Check property `valid` for validity of IBAN. 

            Note: An HTTP status 200 means that the HTTP request and response were successful, NOT that the IBAN is valid.
          content:
            application/json:
              schema:
                type: object
                description: ''
                properties:
                  data:
                    type: object
                    required:
                      - iban
                      - valid
                    properties:
                      iban:
                        type: string
                        description: The IBAN to validate
                      valid:
                        type: boolean
                        description: Is the IBAN valid?
                  meta:
                    $ref: '#/components/schemas/Meta'
                  valid_more:
                    $ref: '#/components/schemas/Validations'
                required:
                  - data
                  - meta
              examples:
                Example of passed validation:
                  value:
                    data:
                      iban: DE89370400440532013000
                      valid: 'true'
                    status:
                      code: 10210
                      message: Valid IBAN
                      more_info: ''
                Example of a failed validation:
                  value:
                    data:
                      iban: DX89370400440532013000
                      valid: 'false'
                    status:
                      code: 10422
                      message: Invalid IBAN
                      more_info: Input is not a valid IBAN. See `valid_more` for more information.
                    valid_more:
                      country_valid: 'false'
                      bban_length_valid: 'false'
                      iban_length_valid: 'false'
                      bban_format_valid: 'false'
                      iban_format_valid: 'false'
                      iban_checksum_valid: 'false'
                      national_checksum_valid: 'false'
                      iban_suggest: DE89370400440532013000
      security:
        - API-key: []
    parameters:
      - schema:
          type: string
          format: ''
          deprecated: false
          minLength: ''
          maxLength: ''
        name: iban
        in: path
        description: A candidate IBAN to validate
        required: true
  '/ibans/{iban}':
    parameters:
      - schema:
          type: string
        name: iban
        in: path
        required: true
    get:
      summary: Get details for an IBAN
      tags:
        - ibans
      responses:
        '200':
          description: The IBAN is valid and its components are returned
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  iban:
                    type: string
                    description: The IBAN from the request
                  meta:
                    $ref: '#/components/schemas/Meta'
                  details:
                    $ref: '#/components/schemas/IbanDetails'
                required:
                  - iban
                  - meta
              examples:
                Example of IBAN details:
                  value:
                    iban: GB29NWBK60161331926719
                    status:
                      code: '200'
                      message: OK
                      more_info: ''
                    details:
                      country_code: GB
                      bank_id: NWBK
                      branch_id: '601613'
                      account_number: '31926719'
                      checksum: '29'
        '422':
          description: |-
            The IBAN is invalid, so its components cannot be returned. The properties of response object "details" will be empty. 

            You may wish to try method `/ibans/{iban}/validity` to determine which part of the IBAN is invalid.
          content:
            application/json:
              schema:
                type: object
                properties:
                  iban:
                    type: string
                  meta:
                    $ref: '#/components/schemas/Meta'
              examples:
                Example of response to IBAN whose details cannot be extracted:
                  value:
                    iban: DE89370400440000
                    status:
                      code: '422'
                      message: Unprocessable Entity
                      more_info: Invalid IBAN
      operationId: getIbanDetails
      description: |-
        Given a valid IBAN, returns its component parts.

        Example:

        ```bash
        curl --request GET \
        --url 'https://api.ibanfox.com/v1/ibans/DE89370400440532013000'  \
        --header 'x-api-key: 46w4e65e4q54e6'
        ```
      security:
        - API-key: []
components:
  schemas:
    Validations:
      title: Validation suite
      type: object
      x-examples: {}
      description: ''
      x-tags:
        - models
      properties:
        country_valid:
          type: boolean
          description: Do first two characters represent a valid IBAN country?
        bban_length_valid:
          type: boolean
          description: Is the BBAN implicit in the IBAN of a valid length for the country?
        iban_length_valid:
          type: boolean
          description: Is the IBAN length valid for the country?
        bban_format_valid:
          type: boolean
          description: Is the BBAN implicit in the IBAN of a valid format for the country?
        iban_format_valid:
          type: boolean
          description: Is the IBAN format valid?
        iban_checksum_valid:
          type: boolean
          description: Is the IBAN checksum valid?
        national_checksum_valid:
          type: boolean
          description: Is the national checksum valid for the country?
        iban_suggest:
          type: string
          description: 'In case of a failed validation, this field attempts to provide a workable correction. Do not take this suggestion too seriously, and certainly DO NOT RELY ON IT for transferring funds.'
    Meta:
      title: Meta
      type: object
      x-tags:
        - models
      properties:
        code:
          type: number
          description: Internal response code
        message:
          type: string
          description: Internal response description
        more_info:
          type: string
          description: 'More information about the result, if available'
      required:
        - code
        - message
        - more_info
    IbanDetails:
      title: IbanDetails
      type: object
      x-tags:
        - models
      properties:
        country_code:
          type: string
        checksum:
          type: string
        bank_id:
          type: string
        branch_id:
          type: string
        account_number:
          type: string
      required:
        - country_code
        - checksum
        - bank_id
        - branch_id
        - account_number
  securitySchemes:
    API-key:
      name: x-api-key
      type: apiKey
      in: header
      description: 'To use this API, an API key is required. Get one for free at [https://ibanfox.com/register](https://ibanfox.com/register).'
externalDocs:
  description: "\U0001F4D6 IBANfox Documentation"
  url: 'https://ibanfox.com/docs'
security:
  - API Key - 1: []
